# Generated by Django 5.0.3 on 2024-03-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_family_delete_person_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_family_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='kindred',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
